# Generated by Django 5.2 on 2025-10-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('pickup_address', models.TextField(help_text='Address to pick up the package')),
                ('delivery_address', models.TextField(help_text='Address to deliver the package')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=10)),
                ('tracking_number', models.CharField(editable=False, help_text='Unique tracking number for this shipment', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', help_text='Current status of the shipment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the shipment')),
                ('courier', models.ForeignKey(blank=True, help_text='Courier assigned to this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_assigned', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(help_text='User who is sending the package', on_delete=django.db.models.deletion.CASCADE, related_name='shipments_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
