# Generated by Django 4.2.7 on 2025-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, help_text='When the verification token was created', null=True),
        ),
    ]
