# Generated by Django 4.2.7 on 2025-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason for hold (e.g., customs clearance, regulatory issues)', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Previous status before current status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('hold', 'Hold'), ('delivered', 'Delivered')], default='pending', help_text='Current status of the shipment', max_length=20),
        ),
    ]
