# Generated by Django 4.2.7 on 2025-10-14 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shipment_hold_reason_shipment_previous_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatusNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('hold', 'Hold'), ('delivered', 'Delivered')], help_text='Status at the time of this note', max_length=20)),
                ('note', models.TextField(help_text='Admin note describing the current status or update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this note was created')),
                ('created_by', models.ForeignKey(help_text='Admin who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_notes_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(help_text='Shipment this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_notes', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Status Note',
                'verbose_name_plural': 'Shipment Status Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
