# Generated by Django 4.2.7 on 2025-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shipmentstatusnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token_created_at',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('hold', 'Hold'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', help_text='Current status of the shipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentstatusnote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('hold', 'Hold'), ('delivered', 'Delivered'), ('returned', 'Returned')], help_text='Status at the time of this note', max_length=20),
        ),
    ]
