# Generated by Django 4.2.7 on 2025-10-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question or query', max_length=500)),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for matching (e.g., track, tracking, shipment)')),
                ('category', models.CharField(choices=[('shipping', 'Shipping'), ('tracking', 'Tracking'), ('delivery', 'Delivery'), ('refund', 'Refund'), ('pickup', 'Pickup'), ('pricing', 'Pricing'), ('account', 'Account'), ('general', 'General')], default='general', help_text='Category of the FAQ', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text='Name for anonymous customers', max_length=255)),
                ('status', models.CharField(choices=[('bot', 'Bot Only'), ('waiting', 'Waiting for Agent'), ('active', 'Active with Agent'), ('closed', 'Closed')], default='bot', help_text='Current status of the chat session', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('agent_joined_at', models.DateTimeField(blank=True, help_text='When agent joined the chat', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the chat session ended', null=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Assigned customer support agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (can be null for anonymous users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('agent', 'Agent'), ('system', 'System')], help_text='Who sent this message', max_length=20)),
                ('message', models.TextField(help_text='The message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent the message (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
